# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ['pomodoro_app.py'],
    pathex=[],
    binaries=[],
    datas=[('static/icon.png','static'),('static/tomato.ico','static')],
    hiddenimports=['PIL','PIL.Image','pystray'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter.test','unittest','email','http','flask','jinja2','markupsafe','webview','pythonnet'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Pomodoro',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='static/tomato.ico',
)
